import { Inter } from "next/font/google";
import "./globals.css";
// import ThemeProvider from "@/components/DarkModeTheme/ThemeProvider";
// import ThemeSwitcher from "@/components/DarkModeTheme/ThemeSwitcher";
const inter = Inter({ subsets: ["latin"] });
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white dark:bg-black ${inter.className}`}>
        {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}
        {/* <ThemeSwitcher /> */}
        <SessionProvider>
          <main>{children}</main>
        </SessionProvider>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
