import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import AuthProviders from "@/components/AuthProvider/AuthProviders";

import { ThemeProvider } from "../context/theme-context";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body> */}
      <ThemeProvider>
        <body>
          <main>
            <AuthProviders>{children}</AuthProviders>
          </main>
        </body>
      </ThemeProvider>
    </html>
  );
}

export default RootLayout;
